AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "ETL Training - Athena"

Parameters:
    S3Name:
        Type: 'String'
        Default: 'minfante-etl-training'
    Schema:
        Type: 'String'

Globals:
    Function:
        Timeout: 30
        Runtime: python3.8
        Environment:
            Variables:
                DATA_PREFIX: "data"
                DATA_FILE_NAME: "raw_data.csv"

Resources:
################# Lamba Layers ###################
    CommonsLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: common-layer
            Description: "Common modules"
            RetentionPolicy: Delete
            CompatibleRuntimes:
                - python3.8
            ContentUri: ./lambda-layer/
################# S3 BUCKET ######################
    S3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete 
        Properties:
            BucketName: !Ref S3Name

    FillBucketLambda:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub '${AWS::StackName}-fill-bucket-lambda'
            CodeUri: lambda/fill_bucket_lambda/
            Handler: fill_bucket_lambda.lambda_handler
            Layers:
                - !Ref CommonsLayer
            Policies:
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - 's3:*'
                        Resource: !Sub "arn:aws:s3:::${S3Name}*"
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - 'cloudwatch:*'
                            - 'logs:*'
                        Resource: '*'
            Environment:
                Variables:
                    BUCKET_NAME: !Ref S3Bucket
                    BUCKET_ARN: !GetAtt S3Bucket.Arn
################ Step Function ####################
    EtlPipeline:
        Type: AWS::Serverless::StateMachine
        Properties:
            Name: !Sub '${AWS::StackName}-etl-pipeline'
            DefinitionUri: step-function/etl-pipeline.json
            #DefinitionSubstitutions:
            Role: !GetAtt EtlPipelineRole.Arn
    EtlPipelineRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - !Sub states.${AWS::Region}.amazonaws.com
                      Action:
                          - 'sts:AssumeRole'
            Policies:
                - PolicyName: !Sub '${AWS::StackName}-etl-pipeline-policy'
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                        - Effect: Allow
                          Action:
                              - logs:GetLogEvents
                              - logs:PutLogEvents
                              - logs:CreateLogStream
                              - logs:DescribeLogStreams
                              - logs:PutRetentionPolicy
                              - logs:CreateLogGroup
                          Resource: "*"
    TriggerPipelineLambda:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub '${AWS::StackName}-trigger-pipeline'
            CodeUri: lambda/trigger_pipeline_lambda/
            Handler: trigger_pipeline_lambda.lambda_handler
            Environment:
                Variables:
                    STATE_MACHINE_ARN: !GetAtt EtlPipeline.Arn
            Layers:
                - !Ref CommonsLayer
            Policies:
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - 's3:*'
                        Resource: !Sub "arn:aws:s3:::${S3Name}*"
                      - Effect: Allow
                        Action:
                            - 'states:StartExecution'
                        Resource: !GetAtt EtlPipeline.Arn
                      - Effect: Allow
                        Action:
                            - 'cloudwatch:*'
                            - 'logs:*'
                        Resource: '*'
            Events:
                ObjectCreatedEvent:
                    Type: S3
                    Properties:
                        Bucket: !Ref S3Bucket
                        Events: s3:ObjectCreated:*
                        Filter:
                            S3Key:
                                Rules:
                                    - Name: prefix
                                      Value: "data"
